name: DisGeneFormer_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - bzip2
  - ca-certificates
  - cudatoolkit
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libpng
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuv
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - ninja
  - ninja-base
  - numpy
  - numpy-base
  - openh264
  - openssl
  - pillow
  - pip
  - python=3.11.9
  - readline
  - setuptools
  - sqlite
  - tbb
  - tk
  - typing_extensions
  - wheel
  - xz
  - zlib
  - zstd
  - seaborn
  - pip:
    - async-lru
    - async-timeout
    - attrs
    - babel
    - beautifulsoup4
    - bleach
    - certifi
    - click
    - debugpy
    - gdown
    - ipykernel
    - ipython
    - jedi
    - networkx
    - numpy==2.2.4
    - packaging
    - pandas
    - pyarrow
    - pycparser
    - pygments
    - pyparsing
    - python-box
    - pywavelets
    - pyyaml
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboardx
    - torch==2.3.1
    - torch-geometric==2.5.3
    - tqdm
